### ISSUE TITLE
VCF (caller) concordance analysis using jasmine

### ISSUE THREAD

**Issue by am8265** [mkirsche/Jasmine#30]
Hello,

Would you recommend this tool for SV VCF caller concordance analysis on Truth Set ? I have actually used this
with `max_dist_linear=0.1 min_dist=50` parameters, and used the SUPP_VEC field of the output vcf. Could this be a good approach beside other tools like this https://github.com/spiralgenetics/truvari ?

Thanks !

**Comment by mkirsche** [comment]
Hi,

Yes, that absolutely sounds like a good application for Jasmine!  In our work we have used it to measure SV agreement to compare to ground truth, as well as to measure concordance across technologies and callers, and it has been useful for benchmarking in all of those settings. One note if you're comparing across callers is that you may need to use the --ignore_strand command line flag, particularly if comparing between Sniffles and other SV callers. 

Feel free to reach out here if you have any further questions or encounter any issues using Jasmine for your concordance analysis!

Melanie
