### ISSUE TITLE
SUPP INFO tag should be Integer

### ISSUE THREAD

**Issue by fgvieira** [mkirsche/Jasmine#33]
In `jasmine`'s output VCF file, both `SUPP` and `SUPP_EXT` are set as `String`:

```
##INFO=<ID=SUPP,Number=1,Type=String,Description="Number of samples supporting the variant">
##INFO=<ID=SUPP_EXT,Number=1,Type=String,Description="Number of samples supporting the variant, potentially extended across multiple merges">
```

However, shouldn't they be set to `Integer`?

**Comment by mkirsche** [comment]
Thank you for pointing this out! I have updated this in the Github repo so the changes will be incorporated in the next release.

Thanks!
Melanie
