### ISSUE TITLE
Java OutOfMemoryError

### ISSUE THREAD

**Issue by prometheusloong** [mkirsche/Jasmine#35]
Hi,
    When i try to merge 33 vcf from SyRI (about 2,000,000 variants per sample), i got this errror:
`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects`
    And it output like this:
`syri.vcf has 2051564 variants
syri.vcf has 1968258 variants
syri.vcf has 3679710 variants
syri.vcf has 3842100 variants
syri.vcf has 3772814 variants
syri.vcf has 1718254 variants
syri.vcf has 3279550 variants
syri.vcf has 1932339 variants
syri.vcf has 3027315 variants
syri.vcf has 3343637 variants
syri.vcf has 3623126 variants
syri.vcf has 2107628 variants
syri.vcf has 3640813 variants
syri.vcf has 2628045 variants`
    How can i do?
`jasmine file_list=sv.file out_file=merged.vcf max_dist_linear=0.5 min_dist=100 kd_tree_norm=2 spec_len=50 min_overlap=0.9`

**Comment by mkirsche** [comment]
Hi,

Thanks for your interest in using Jasmine! This error typically means that the memory usage is too high for your system. One work-around which has worked for other users is to split each of the VCFs by chromosome and run Jasmine separately on each chromosome. If you build Jasmine from the Github repository, you can do that with this script: https://github.com/mkirsche/Jasmine/blob/master/split_jasmine. You can see usage instructions by running it with no parameters, and more details about it in the discussion on this issue https://github.com/mkirsche/Jasmine/issues/18.

I hope that helps!
Melanie

**Comment by prometheusloong** [comment]
Thank you, it works for me
