### ISSUE TITLE
Jasmine doesn't work with Smoove

### ISSUE THREAD

**Issue by teresa1997** [mkirsche/Jasmine#36]
Hello!
I'm using Jasmine to merge vcf files obtained from different tools of the same sample. Those are the tools that I'm currently using: Manta, Delly, Whamg, Svaba and Smoove.
I can merge all the tools without problems except for smoove. When I put smoove with the others, Jasmine can merge but smoove ramains always as a single call even if there are variants in common. 
I tried to merge smoove aginst itself (with another sample) and it's working. I also tried to merge Smoove against each one of the other tool and it's not working. 
Those are the parameter that I'm using: 

```
jasmine
file_list=ID.tool.txt
out_file=ID.vcf
genome_file=Homo_sapiens_assembly38.fasta
bam_list=ID.bam.txt
max_dist_linear=1.0
threads=16
min_overlap=0.75
min_support=2
--ignore_type
--normalize_type
```

The INFO field of each VCF is a little bit different but still, the others can be merged together. 
If you want I can send you the different vcf via email.

**Comment by teresa1997** [comment]
I tried with the --ignore_strand parameter and now it's working. Thank you for your kindness Melanie!!!

**Comment by mkirsche** [comment]
No problem - I'm glad that helped!!

Melanie
