### ISSUE TITLE
Matches to the reference instead of missing data

### ISSUE THREAD

**Issue by MehmetGoktay** [mkirsche/Jasmine#6]
Hi,

I would like to use Jasmine to merge Sniffles vcf outputs. The major problem I see is that, Jasmine most of the times it only outputs missing data for the samples that did not identify SV entries. 

Is there a way to force Jasmine to check if it is a real missing data or matches to the reference 0/0? Or should I treat any missing data as matches to the reference after using Jasmine?

Like this example: Chr3	5797105	0_4943	GTTCAATCTTCGTCTTGTTTCTATTTGAGATTGAAGTTGAAATTATGCTCGATCTGTTCTGTAGCTAGAATT	N	.	PASS	PRECISE;SVMETHOD=JASMINE;CHR2=Chr3;END=5797176;STD_quant_start=0.000000;STD_quant_stop=0.000000;Kurtosis_quant_start=4.523800;Kurtosis_quant_stop=1.082952;SVTYPE=DEL;SUPTYPE=AL;SVLEN=-71;STRANDS=+-;RE=81;REF_strand=0,0;AF=1;STARTVARIANCE=0.000000;ENDVARIANCE=0.000000;AVG_LEN=-72.000000;AVG_START=5797105.000000;AVG_END=5797177.000000;SUPP_VEC_EXT=1010000010000;IDLIST_EXT=4943,5641,6674;SUPP_EXT=3;SUPP_VEC=1010000010000;SUPP=3;IDLIST=4943,5641,6674	GT:IS:OT:OS	1/1:.:DEL:.	./.:NA:NA:NA	1/1:.:DEL:.	./.:NA:NA:NA	./.:NA:NA:NA	./.:NA:NA:NA	./.:NA:NA:NA	./.:NA:NA:NA	1/1:.:DEL:.	./.:NA:NA:NA	./.:NA:NA:NA	./.:NA:NA:NA	./.:NA:NA:NA

Best Regards,
Mehmet

**Comment by mkirsche** [comment]
Hi Mehmet,

Jasmine will only output missing data (./. genotype) if there is no vcf entry in a particular sample at that site.  If there is a 0/0 entry present in the input data, the same 0/0 genotype will be output.

As for interpretting the output, it's generally safe to assume that the lack of a variant call corresponds to a match to the reference.  Checking for 0/0 genotypes and filtering those out can be done either before or after running Jasmine

Hope that answers your question! 
Melanie

**Comment by MehmetGoktay** [comment]
Hey Melanie.

Yes it does. 

Thank you very much,
Mehmet
