### ISSUE TITLE
Problem with --output_genotypes parameter

### ISSUE THREAD

**Issue by mldmort** [mkirsche/Jasmine#8]
Hi,

I've noticed that when I'm running Jasmine with parameter: `--output_genotypes` I get an error as following:
```
Exception in thread "main" java.lang.NullPointerException
    at AddGenotypes.addGenotypes(AddGenotypes.java:150)
    at PipelineManager.addGenotypes(PipelineManager.java:191)
    at Main.postprocess(Main.java:91)
    at Main.main(Main.java:27)
```
And Jasmine does not finish the job, and writes just part of the calls in the output file. Without `--output_genotypes` Jasmine doesn't have any problems and finishes, but doesn't output genotypes in the merged output VCF file.

I only have these genotypes in my VCF files (generated by Sniffles):
```
0/0
0/1
1/1
```

Any idea what can be the problem?
Thanks,

**Comment by mkirsche** [comment]
I think you accidentally opened this issue twice at the same time, so I'm going to go ahead and close this one and point to https://github.com/mkirsche/Jasmine/issues/9
